# ReadTheDocs configuration file.
#
# See https://docs.readthedocs.io/en/stable/config-file/v2.html?#conda for
# details.
version: 2

sphinx:
    configuration: docs/source/conf.py

conda:
    environment: docs/environment-rtd.yml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_install:
      - pip install .
