FROM debian:buster

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        gfortran \
        git \
        libc6-dev \
        libc6 \
        libblas3 \
        liblapack3 \
        mercurial \
        subversion \
        tox \
        unzip \
        wget
